# Data
data_dir: "../data"
dtype: "kdd17"
n_train_stock: 40  # number of training stocks to construct the universe
n_sample:   # number of samples per window size and per single stock
n_lag: 1
n_stock: 1  # number of iteration(stock) to sample per window size, total will be `n_stocks` * `n_sample`
keep_support_history: true  # query data will starting from support starting date
show_y_index: false  # for debug purpose

# Model
feature_size: 11
hidden_size: 20 
output_size: 1  # 1 == 2 setting
num_layers: 1
drop_rate: 0.3
inner_lr_init: 0.1
finetuning_lr_init: 0.1

# Trainer
log_dir: './logging'
total_steps: 100
n_inner_step: 5
n_finetuning_step: 5
n_valid_step: 5
every_valid_step: 5
beta: 0.001
gamma: 1.0e-9
lambda1: 1.0e-8
lambda2: 0.1
outer_lr: 0.0001
clip_value: 0.1
device: 'cuda'
print_step: 5
